/********************************************************************
* G__SCN.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__SCN.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__SCN();
extern void G__cpp_setup_inheritanceG__SCN();
extern void G__cpp_setup_typetableG__SCN();
extern void G__cpp_setup_memvarG__SCN();
extern void G__cpp_setup_globalG__SCN();
extern void G__cpp_setup_memfuncG__SCN();
extern void G__cpp_setup_funcG__SCN();
extern void G__set_cpp_environmentG__SCN();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./AIDA_Structs.h"
#include "./FATIMA_Detector_System.h"
#include "./FATIMA_Energy_Calibration.h"
#include "./FATIMA_Gain_Match.h"
#include "./FATIMA_Time_Calibration.h"
#include "./FEBEX.h"
#include "./First_Test.h"
#include "./GALILEO_Detector_System_TEST.h"
#include "./GALILEO_Energy_Calibration.h"
#include "./GALILEO_Time_Calibration.h"
#include "./PLASTIC_Calibrator.h"
#include "./PLASTIC_Data_Stream.h"
#include "./PLASTIC_Detector_System.h"
#include "./QDC_751.h"
#include "./Raw_Event.h"
#include "./Raw_Event_Storage.h"
#include "./TAMEX.h"
#include "./TDC_1290.h"
#include "./TSCNAnalysis.h"
#include "./TSCNAnlEvent.h"
#include "./TSCNAnlProc.h"
#include "./TSCNCalEvent.h"
#include "./TSCNCalProc.h"
#include "./TSCNParameter.h"
#include "./TSCNUnpackEvent.h"
#include "./White_Rabbit.h"
#include "./WR_Structure.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__SCNLN_TClass;
extern G__linked_taginfo G__G__SCNLN_TBuffer;
extern G__linked_taginfo G__G__SCNLN_TMemberInspector;
extern G__linked_taginfo G__G__SCNLN_TObject;
extern G__linked_taginfo G__G__SCNLN_TNamed;
extern G__linked_taginfo G__G__SCNLN_string;
extern G__linked_taginfo G__G__SCNLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__SCNLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__SCNLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__SCNLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__SCNLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__SCNLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__SCNLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__SCNLN_TH1D;
extern G__linked_taginfo G__G__SCNLN_TH1;
extern G__linked_taginfo G__G__SCNLN_Raw_Event;
extern G__linked_taginfo G__G__SCNLN_Data_Stream;
extern G__linked_taginfo G__G__SCNLN_Detector_System;
extern G__linked_taginfo G__G__SCNLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__SCNLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__SCNLN_TH2;
extern G__linked_taginfo G__G__SCNLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__SCNLN_TGo4Picture;
extern G__linked_taginfo G__G__SCNLN_TGo4EventSource;
extern G__linked_taginfo G__G__SCNLN_TGo4EventElement;
extern G__linked_taginfo G__G__SCNLN_TGo4MbsEvent;
extern G__linked_taginfo G__G__SCNLN_TSCNUnpackEvent;
extern G__linked_taginfo G__G__SCNLN_maplEpairlEintcOintgRcOintcOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOintgRsPgRsPgR;
extern G__linked_taginfo G__G__SCNLN_White_Rabbit;
extern G__linked_taginfo G__G__SCNLN_TGo4WinCond;
extern G__linked_taginfo G__G__SCNLN_TGo4Parameter;
extern G__linked_taginfo G__G__SCNLN_TGo4EventProcessor;
extern G__linked_taginfo G__G__SCNLN_TSCNUnpackProc;
extern G__linked_taginfo G__G__SCNLN_TGo4CommandReceiver;
extern G__linked_taginfo G__G__SCNLN_TGo4Analysis;
extern G__linked_taginfo G__G__SCNLN_TSCNParameter;
extern G__linked_taginfo G__G__SCNLN_TSCNCalEvent;
extern G__linked_taginfo G__G__SCNLN_TSCNAnlEvent;
extern G__linked_taginfo G__G__SCNLN_TSCNAnalysis;
extern G__linked_taginfo G__G__SCNLN_TSCNAnlProc;
extern G__linked_taginfo G__G__SCNLN_TSCNCalProc;

/* STUB derived class for protected member access */
