/********************************************************************
* G__SCN.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__SCN.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__SCN();
extern void G__cpp_setup_inheritanceG__SCN();
extern void G__cpp_setup_typetableG__SCN();
extern void G__cpp_setup_memvarG__SCN();
extern void G__cpp_setup_globalG__SCN();
extern void G__cpp_setup_memfuncG__SCN();
extern void G__cpp_setup_funcG__SCN();
extern void G__set_cpp_environmentG__SCN();
}


#include "/tmp/rootcint_UGvl7B.h"
