//
// File generated by /cvmfs/csee.gsi.de/root/534-36/bin/rootcint at Thu Jun 21 11:29:48 2018

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME G__Go4ExampleSimple
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "G__Go4ExampleSimple.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void Tx7_Param_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_Tx7_Param(void *p = 0);
   static void *newArray_Tx7_Param(Long_t size, void *p);
   static void delete_Tx7_Param(void *p);
   static void deleteArray_Tx7_Param(void *p);
   static void destruct_Tx7_Param(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::Tx7_Param*)
   {
      ::Tx7_Param *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Tx7_Param >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Tx7_Param", ::Tx7_Param::Class_Version(), "././Tx7_Param.h", 25,
                  typeid(::Tx7_Param), ::ROOT::DefineBehavior(ptr, ptr),
                  &::Tx7_Param::Dictionary, isa_proxy, 4,
                  sizeof(::Tx7_Param) );
      instance.SetNew(&new_Tx7_Param);
      instance.SetNewArray(&newArray_Tx7_Param);
      instance.SetDelete(&delete_Tx7_Param);
      instance.SetDeleteArray(&deleteArray_Tx7_Param);
      instance.SetDestructor(&destruct_Tx7_Param);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::Tx7_Param*)
   {
      return GenerateInitInstanceLocal((::Tx7_Param*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Tx7_Param*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void First_Test_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_First_Test(void *p = 0);
   static void *newArray_First_Test(Long_t size, void *p);
   static void delete_First_Test(void *p);
   static void deleteArray_First_Test(void *p);
   static void destruct_First_Test(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::First_Test*)
   {
      ::First_Test *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::First_Test >(0);
      static ::ROOT::TGenericClassInfo 
         instance("First_Test", ::First_Test::Class_Version(), "././First_Test.h", 26,
                  typeid(::First_Test), ::ROOT::DefineBehavior(ptr, ptr),
                  &::First_Test::Dictionary, isa_proxy, 4,
                  sizeof(::First_Test) );
      instance.SetNew(&new_First_Test);
      instance.SetNewArray(&newArray_First_Test);
      instance.SetDelete(&delete_First_Test);
      instance.SetDeleteArray(&deleteArray_First_Test);
      instance.SetDestructor(&destruct_First_Test);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::First_Test*)
   {
      return GenerateInitInstanceLocal((::First_Test*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::First_Test*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr Tx7_Param::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *Tx7_Param::Class_Name()
{
   return "Tx7_Param";
}

//______________________________________________________________________________
const char *Tx7_Param::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::Tx7_Param*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Tx7_Param::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::Tx7_Param*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Tx7_Param::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::Tx7_Param*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Tx7_Param::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::Tx7_Param*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr First_Test::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *First_Test::Class_Name()
{
   return "First_Test";
}

//______________________________________________________________________________
const char *First_Test::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::First_Test*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int First_Test::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::First_Test*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void First_Test::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::First_Test*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *First_Test::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::First_Test*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void Tx7_Param::Streamer(TBuffer &R__b)
{
   // Stream an object of class Tx7_Param.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(Tx7_Param::Class(),this);
   } else {
      R__b.WriteClassBuffer(Tx7_Param::Class(),this);
   }
}

//______________________________________________________________________________
void Tx7_Param::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Tx7_Param.
      TClass *R__cl = ::Tx7_Param::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "caen_group", &caen_group);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "group_mon", &group_mon);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fill", &fill);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "frP1", &frP1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "frP2", &frP2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fiNum", &fiNum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fbEnab", &fbEnab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fdTest", &fdTest);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fsTest", &fsTest);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fcTest", &fcTest);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "flTest", &flTest);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fxInputfile", &fxInputfile);
      R__insp.InspectMember(fxInputfile, "fxInputfile.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fiDataArray[100]", fiDataArray);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fdMeV[5][10]", fdMeV);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fuNum", &fuNum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fdTestarr[5]", fdTestarr);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fuShort", &fuShort);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fuChar", &fuChar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fuLong", &fuLong);
      TGo4Parameter::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_Tx7_Param(void *p) {
      return  p ? new(p) ::Tx7_Param : new ::Tx7_Param;
   }
   static void *newArray_Tx7_Param(Long_t nElements, void *p) {
      return p ? new(p) ::Tx7_Param[nElements] : new ::Tx7_Param[nElements];
   }
   // Wrapper around operator delete
   static void delete_Tx7_Param(void *p) {
      delete ((::Tx7_Param*)p);
   }
   static void deleteArray_Tx7_Param(void *p) {
      delete [] ((::Tx7_Param*)p);
   }
   static void destruct_Tx7_Param(void *p) {
      typedef ::Tx7_Param current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::Tx7_Param

//______________________________________________________________________________
void First_Test::Streamer(TBuffer &R__b)
{
   // Stream an object of class First_Test.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(First_Test::Class(),this);
   } else {
      R__b.WriteClassBuffer(First_Test::Class(),this);
   }
}

//______________________________________________________________________________
void First_Test::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class First_Test.
      TClass *R__cl = ::First_Test::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCr1Ch[8]", &fCr1Ch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCr2Ch[8]", &fCr2Ch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCr1Ch1x2", &fCr1Ch1x2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHis1", &fHis1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHis1gate", &fHis1gate);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHis2", &fHis2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHis2gate", &fHis2gate);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fE_QDC[32]", &fE_QDC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fE_ADC[32]", &fE_ADC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTime[32]", &fTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTime2[32]", &fTime2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTime3[32]", &fTime3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fdTime", &fdTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fconHis1", &fconHis1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fconHis2", &fconHis2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPolyCon", &fPolyCon);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fConArr", &fConArr);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fInput", &fInput);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fParam", &fParam);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPicture", &fPicture);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fcondSet", &fcondSet);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCrate1[8]", fCrate1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCrate2[8]", fCrate2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "E1", &E1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "E2", &E2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T1", &T1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T2", &T2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*gg_tree", &gg_tree);
      TGo4EventProcessor::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_First_Test(void *p) {
      return  p ? new(p) ::First_Test : new ::First_Test;
   }
   static void *newArray_First_Test(Long_t nElements, void *p) {
      return p ? new(p) ::First_Test[nElements] : new ::First_Test[nElements];
   }
   // Wrapper around operator delete
   static void delete_First_Test(void *p) {
      delete ((::First_Test*)p);
   }
   static void deleteArray_First_Test(void *p) {
      delete [] ((::First_Test*)p);
   }
   static void destruct_First_Test(void *p) {
      typedef ::First_Test current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::First_Test

/********************************************************
* G__Go4ExampleSimple.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableG__Go4ExampleSimple();

extern "C" void G__set_cpp_environmentG__Go4ExampleSimple() {
  G__cpp_reset_tagtableG__Go4ExampleSimple();
}
#include <new>
extern "C" int G__cpp_dllrevG__Go4ExampleSimple() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Tx7_Param */
static int G__G__Go4ExampleSimple_188_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Tx7_Param* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Tx7_Param[n];
     } else {
       p = new((void*) gvp) Tx7_Param[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Tx7_Param;
     } else {
       p = new((void*) gvp) Tx7_Param;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_188_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Tx7_Param* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new Tx7_Param((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) Tx7_Param((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_188_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Tx7_Param::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_188_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Tx7_Param::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_188_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Tx7_Param::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_188_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Tx7_Param::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_188_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Tx7_Param*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_188_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Tx7_Param::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_188_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Tx7_Param::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_188_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Tx7_Param::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_188_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Tx7_Param::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__G__Go4ExampleSimple_188_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Tx7_Param* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Tx7_Param(*(Tx7_Param*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Tx7_Param G__TTx7_Param;
static int G__G__Go4ExampleSimple_188_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Tx7_Param*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Tx7_Param*) (soff+(sizeof(Tx7_Param)*i)))->~G__TTx7_Param();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Tx7_Param*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Tx7_Param*) (soff))->~G__TTx7_Param();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__G__Go4ExampleSimple_188_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Tx7_Param* dest = (Tx7_Param*) G__getstructoffset();
   *dest = *(Tx7_Param*) libp->para[0].ref;
   const Tx7_Param& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* First_Test */
static int G__G__Go4ExampleSimple_639_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   First_Test* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new First_Test[n];
     } else {
       p = new((void*) gvp) First_Test[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new First_Test;
     } else {
       p = new((void*) gvp) First_Test;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_639_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   First_Test* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new First_Test((const char*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) First_Test((const char*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_639_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) First_Test::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_639_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) First_Test::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_639_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) First_Test::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_639_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      First_Test::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_639_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((First_Test*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_639_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) First_Test::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_639_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) First_Test::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_639_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) First_Test::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__Go4ExampleSimple_639_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) First_Test::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__G__Go4ExampleSimple_639_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   First_Test* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new First_Test(*(First_Test*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef First_Test G__TFirst_Test;
static int G__G__Go4ExampleSimple_639_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (First_Test*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((First_Test*) (soff+(sizeof(First_Test)*i)))->~G__TFirst_Test();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (First_Test*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((First_Test*) (soff))->~G__TFirst_Test();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__G__Go4ExampleSimple_639_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   First_Test* dest = (First_Test*) G__getstructoffset();
   *dest = *(First_Test*) libp->para[0].ref;
   const First_Test& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Tx7_Param */

/* First_Test */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncG__Go4ExampleSimple {
 public:
  G__Sizep2memfuncG__Go4ExampleSimple(): p(&G__Sizep2memfuncG__Go4ExampleSimple::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncG__Go4ExampleSimple::*p)();
};

size_t G__get_sizep2memfuncG__Go4ExampleSimple()
{
  G__Sizep2memfuncG__Go4ExampleSimple a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceG__Go4ExampleSimple() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param))) {
     Tx7_Param *G__Lderived;
     G__Lderived=(Tx7_Param*)0x1000;
     {
       TGo4Parameter *G__Lpbase=(TGo4Parameter*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param),G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TGo4Parameter),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param),G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param),G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test))) {
     First_Test *G__Lderived;
     G__Lderived=(First_Test*)0x1000;
     {
       TGo4EventProcessor *G__Lpbase=(TGo4EventProcessor*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test),G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TGo4EventProcessor),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGo4EventSource *G__Lpbase=(TGo4EventSource*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test),G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TGo4EventSource),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test),G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test),G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableG__Go4ExampleSimple() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Tx7_Param */
static void G__setup_memvarTx7_Param(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param));
   { Tx7_Param *p; p=(Tx7_Param*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->caen_group)-(long)(p)),115,0,0,-1,-1,-1,1,"caen_group=",0,"control");
   G__memvar_setup((void*)((long)(&p->group_mon)-(long)(p)),115,0,0,-1,-1,-1,1,"group_mon=",0,"monitor");
   G__memvar_setup((void*)((long)(&p->fill)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fill=",0,"control filling");
   G__memvar_setup((void*)((long)(&p->frP1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"frP1=",0,"control frP1");
   G__memvar_setup((void*)((long)(&p->frP2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"frP2=",0,"control frP2");
   G__memvar_setup((void*)((long)(&p->fiNum)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fiNum=",0,"control fiNum");
   G__memvar_setup((void*)((long)(&p->fbEnab)-(long)(p)),103,0,0,-1,G__defined_typename("Bool_t"),-1,1,"fbEnab=",0,"control");
   G__memvar_setup((void*)((long)(&p->fdTest)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"fdTest=",0,"control");
   G__memvar_setup((void*)((long)(&p->fsTest)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"fsTest=",0,"control");
   G__memvar_setup((void*)((long)(&p->fcTest)-(long)(p)),99,0,0,-1,G__defined_typename("Char_t"),-1,1,"fcTest=",0,"control");
   G__memvar_setup((void*)((long)(&p->flTest)-(long)(p)),108,0,0,-1,G__defined_typename("Long_t"),-1,1,"flTest=",0,"control");
   G__memvar_setup((void*)((long)(&p->fxInputfile)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TString),-1,-1,1,"fxInputfile=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fiDataArray)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fiDataArray[100]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fdMeV)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"fdMeV[5][10]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fuNum)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"fuNum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fdTestarr)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"fdTestarr[5]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fuShort)-(long)(p)),114,0,0,-1,G__defined_typename("UShort_t"),-1,1,"fuShort=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fuChar)-(long)(p)),98,0,0,-1,G__defined_typename("UChar_t"),-1,1,"fuChar=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fuLong)-(long)(p)),107,0,0,-1,G__defined_typename("ULong_t"),-1,1,"fuLong=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* First_Test */
static void G__setup_memvarFirst_Test(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test));
   { First_Test *p; p=(First_Test*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TH1I),-1,-1,4,"fCr1Ch[8]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TH1I),-1,-1,4,"fCr2Ch[8]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TH2I),-1,-1,4,"fCr1Ch1x2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TH1I),-1,-1,4,"fHis1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TH1I),-1,-1,4,"fHis1gate=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TH1I),-1,-1,4,"fHis2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TH1I),-1,-1,4,"fHis2gate=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TH1I),-1,-1,4,"fE_QDC[32]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TH1I),-1,-1,4,"fE_ADC[32]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TH1I),-1,-1,4,"fTime[32]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TH1I),-1,-1,4,"fTime2[32]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TH1I),-1,-1,4,"fTime3[32]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TH1I),-1,-1,4,"fdTime=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TGo4WinCond),-1,-1,4,"fconHis1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TGo4WinCond),-1,-1,4,"fconHis2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TGo4PolyCond),-1,-1,4,"fPolyCon=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TGo4CondArray),-1,-1,4,"fConArr=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TGo4MbsEvent),-1,-1,4,"fInput=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param),-1,-1,4,"fParam=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TGo4Picture),-1,-1,4,"fPicture=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TGo4Picture),-1,-1,4,"fcondSet=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fCrate1[8]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"fCrate2[8]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"E1=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"E2=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"T1=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,4,"T2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TTree),-1,-1,4,"gg_tree=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarG__Go4ExampleSimple() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTx7_Param(void) {
   /* Tx7_Param */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param));
   G__memfunc_setup("Tx7_Param",851,G__G__Go4ExampleSimple_188_0_1, 105, G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Tx7_Param",851,G__G__Go4ExampleSimple_188_0_2, 105, G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param), -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintParameter",1454,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"C - 'Text_t' 0 - n i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("UpdateFrom",1015,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "U 'TGo4Parameter' - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__G__Go4ExampleSimple_188_0_5, 85, G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Tx7_Param::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__G__Go4ExampleSimple_188_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Tx7_Param::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__G__Go4ExampleSimple_188_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Tx7_Param::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__G__Go4ExampleSimple_188_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Tx7_Param::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__Go4ExampleSimple_188_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__G__Go4ExampleSimple_188_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Tx7_Param::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__G__Go4ExampleSimple_188_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Tx7_Param::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__G__Go4ExampleSimple_188_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Tx7_Param::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__G__Go4ExampleSimple_188_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Tx7_Param::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("Tx7_Param", 851, G__G__Go4ExampleSimple_188_0_17, (int) ('i'), G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param), -1, 0, 1, 1, 1, 0, "u 'Tx7_Param' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Tx7_Param", 977, G__G__Go4ExampleSimple_188_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__G__Go4ExampleSimple_188_0_19, (int) ('u'), G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_Tx7_Param), -1, 1, 1, 1, 1, 0, "u 'Tx7_Param' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncFirst_Test(void) {
   /* First_Test */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test));
   G__memfunc_setup("First_Test",758,G__G__Go4ExampleSimple_639_0_1, 105, G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("First_Test",758,G__G__Go4ExampleSimple_639_0_2, 105, G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test), -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BuildEvent",1010,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "U 'TGo4EventElement' - 0 - target", "event processing function", (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__G__Go4ExampleSimple_639_0_4, 85, G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&First_Test::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__G__Go4ExampleSimple_639_0_5, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&First_Test::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__G__Go4ExampleSimple_639_0_6, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&First_Test::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__G__Go4ExampleSimple_639_0_7, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&First_Test::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__Go4ExampleSimple_639_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__G__Go4ExampleSimple_639_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&First_Test::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__G__Go4ExampleSimple_639_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&First_Test::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__G__Go4ExampleSimple_639_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&First_Test::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__G__Go4ExampleSimple_639_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&First_Test::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("First_Test", 758, G__G__Go4ExampleSimple_639_0_16, (int) ('i'), G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test), -1, 0, 1, 1, 1, 0, "u 'First_Test' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~First_Test", 884, G__G__Go4ExampleSimple_639_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__G__Go4ExampleSimple_639_0_18, (int) ('u'), G__get_linked_tagnum(&G__G__Go4ExampleSimpleLN_First_Test), -1, 1, 1, 1, 1, 0, "u 'First_Test' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncG__Go4ExampleSimple() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalG__Go4ExampleSimple() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcG__Go4ExampleSimple() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__G__Go4ExampleSimpleLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4Parameter = { "TGo4Parameter" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_Tx7_Param = { "Tx7_Param" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4EventElement = { "TGo4EventElement" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4EventSource = { "TGo4EventSource" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TH1I = { "TH1I" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TH2I = { "TH2I" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4WinCond = { "TGo4WinCond" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4PolyCond = { "TGo4PolyCond" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4CondArray = { "TGo4CondArray" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4Picture = { "TGo4Picture" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4MbsEvent = { "TGo4MbsEvent" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4EventProcessor = { "TGo4EventProcessor" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__G__Go4ExampleSimpleLN_First_Test = { "First_Test" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableG__Go4ExampleSimple() {
  G__G__Go4ExampleSimpleLN_TClass.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TBuffer.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TMemberInspector.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TObject.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TNamed.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TString.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TGo4Parameter.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_Tx7_Param.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TGo4EventElement.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TGo4EventSource.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TH1I.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TH2I.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TGo4WinCond.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TGo4PolyCond.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TGo4CondArray.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TGo4Picture.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TGo4MbsEvent.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TGo4EventProcessor.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TTree.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__G__Go4ExampleSimpleLN_First_Test.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableG__Go4ExampleSimple() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TClass);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TObject);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TNamed);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TString);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TGo4Parameter);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_Tx7_Param),sizeof(Tx7_Param),-1,324864,(char*)NULL,G__setup_memvarTx7_Param,G__setup_memfuncTx7_Param);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TGo4EventElement);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TGo4EventSource);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TH1I);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TH2I);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TGo4WinCond);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TGo4PolyCond);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TGo4CondArray);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TGo4Picture);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TGo4MbsEvent);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TGo4EventProcessor);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TTree);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_TVectorTlEdoublegR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__G__Go4ExampleSimpleLN_First_Test),sizeof(First_Test),-1,324864,(char*)NULL,G__setup_memvarFirst_Test,G__setup_memfuncFirst_Test);
}
extern "C" void G__cpp_setupG__Go4ExampleSimple(void) {
  G__check_setup_version(30051515,"G__cpp_setupG__Go4ExampleSimple()");
  G__set_cpp_environmentG__Go4ExampleSimple();
  G__cpp_setup_tagtableG__Go4ExampleSimple();

  G__cpp_setup_inheritanceG__Go4ExampleSimple();

  G__cpp_setup_typetableG__Go4ExampleSimple();

  G__cpp_setup_memvarG__Go4ExampleSimple();

  G__cpp_setup_memfuncG__Go4ExampleSimple();
  G__cpp_setup_globalG__Go4ExampleSimple();
  G__cpp_setup_funcG__Go4ExampleSimple();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncG__Go4ExampleSimple();
  return;
}
class G__cpp_setup_initG__Go4ExampleSimple {
  public:
    G__cpp_setup_initG__Go4ExampleSimple() { G__add_setup_func("G__Go4ExampleSimple",(G__incsetup)(&G__cpp_setupG__Go4ExampleSimple)); G__call_setup_funcs(); }
   ~G__cpp_setup_initG__Go4ExampleSimple() { G__remove_setup_func("G__Go4ExampleSimple"); }
};
G__cpp_setup_initG__Go4ExampleSimple G__cpp_setup_initializerG__Go4ExampleSimple;

