/********************************************************************
* G__Go4ExampleSimple.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__Go4ExampleSimple.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Go4ExampleSimple();
extern void G__cpp_setup_inheritanceG__Go4ExampleSimple();
extern void G__cpp_setup_typetableG__Go4ExampleSimple();
extern void G__cpp_setup_memvarG__Go4ExampleSimple();
extern void G__cpp_setup_globalG__Go4ExampleSimple();
extern void G__cpp_setup_memfuncG__Go4ExampleSimple();
extern void G__cpp_setup_funcG__Go4ExampleSimple();
extern void G__set_cpp_environmentG__Go4ExampleSimple();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./Tx7_Param.h"
#include "./First_Test.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TClass;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TBuffer;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TMemberInspector;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TObject;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TNamed;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TString;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4Parameter;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_Tx7_Param;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4EventElement;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4EventSource;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TH1I;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TH2I;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4WinCond;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4PolyCond;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4CondArray;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4Picture;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4MbsEvent;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TGo4EventProcessor;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TTree;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__Go4ExampleSimpleLN_First_Test;

/* STUB derived class for protected member access */
